spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1020765082579-h99b9d3chv1fnsflo1n1dlpbt0d2fdhg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
